name: Sync main into develop

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Verify CI Passed for Last Merge from Develop
        run: |
          # Fetch the last merge commit from develop to main
          LAST_MERGE_SHA=$(git log --merges --pretty=format:'%H' -n 1 develop)

          if [ -z "$LAST_MERGE_SHA" ]; then
            echo "No recent merge from develop found, skipping sync."
            exit 1
          fi

          # Check if the last merge commit has a passing status
          CI_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/$LAST_MERGE_SHA/status" | jq -r '.state')

          if [[ "$CI_STATUS" != "success" ]]; then
            echo "CI checks for the last merge from develop to main did NOT pass. Aborting sync."
            exit 1
          fi

          echo "CI checks passed. Proceeding with the sync."

      - name: Pull latest main into develop
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout develop
          git pull origin develop
          git merge --no-edit main
          git push origin develop
